"use client";
import "./gallery.css";
import "./tcg-shell.css";
import "./br-card.css";
import { useEffect, useRef, useState } from "react";
import { CardShell } from "../components/card-shell";

type GalleryCard={name:string;rarity:string;no:string;skill:string;flavor:string;accent:string;palette:string;artwork?:string;completed?:string};
const cardMap:Record<string,GalleryCard>={
  침착맨:{name:"침착맨",rarity:"BR",no:"001",skill:"방구석 토크",flavor:"흐름에 몸을 맡긴 채 의도치 않은 명언을 남긴다.",accent:"#24242b",palette:"violet",artwork:"/cards/chimchakman-super-rare-art.png"},
  랄로:{name:"랄로",rarity:"SUPER RARE",no:"002",skill:"주식과 무지개 무드",flavor:"하락장에도 자신만의 흐름을 보여준다.",accent:"#ff8ca5",palette:"rainbow",artwork:"/cards/ralo-super-rare-art.png"},
  곽튜브:{name:"곽튜브",rarity:"ART RARE",no:"003",skill:"세계 로컬 식사",flavor:"낯선 곳에서 새로운 사람과 이야기를 만난다.",accent:"#57e5ab",palette:"sunset",artwork:"/cards/kwaktube-art-rare-art.png"},
  빠더너스:{name:"빠더너스",rarity:"SUPER RARE",no:"004",skill:"한국 지리 문쌤",flavor:"능청스러운 한마디로 수업을 시작한다.",accent:"#ff8ca5",palette:"violet",artwork:"/cards/moonsanghoon-super-rare-art.png"},
  감스트:{name:"감스트",rarity:"SUPER RARE",no:"005",skill:"축구치킨 광기",flavor:"골이 터지는 순간, 누구보다 먼저 세레머니를 시작한다.",accent:"#ff8ca5",palette:"stadium",artwork:"/cards/gamst-super-rare-art.png"},
  피식대학:{name:"피식대학",rarity:"RARE",no:"006",skill:"성수동 바이브",flavor:"유쾌한 한마디가 도시의 공기를 바꾼다.",accent:"#78bafc",palette:"retro",artwork:"/cards/psick-univ-rare-art.png"},
  숏박스:{name:"숏박스",rarity:"ART RARE",no:"007",skill:"현실 연애 콩트",flavor:"1분 만에 현실의 한 장면을 재현한다.",accent:"#57e5ab",palette:"violet",artwork:"/cards/shortbox-art-rare-art.png"},지무비:{name:"지무비",rarity:"UR",no:"008",skill:"결말 포함 영화",flavor:"영화보다 더 재미있는 목소리로 이야기를 완성한다.",accent:"#f6c65c",palette:"violet",artwork:"/cards/gmovie-ultra-rare-art.png"},말왕:{name:"말왕",rarity:"SUPER RARE",no:"009",skill:"3대 500 괴력",flavor:"한계를 넘는 중량 앞에서 거침없이 전진한다.",accent:"#ff8ca5",palette:"gym",artwork:"/cards/malwang-super-rare-art.png"},보겸:{name:"보겸",rarity:"SUPER RARE",no:"010",skill:"근황 올림픽",flavor:"한 번의 인사로 가장 밝은 순간을 만든다.",accent:"#ff8ca5",palette:"flash",artwork:"/cards/bokyem-super-rare-art.png"},떵개떵:{name:"떵개떵",rarity:"ART RARE",no:"011",skill:"소리 없는 아우성",flavor:"가득한 한 접시를 가장 맛있게 기록한다.",accent:"#57e5ab",palette:"table",artwork:"/cards/tteong-art-rare-art.png"},윤가놈:{name:"윤가놈",rarity:"SUPER RARE",no:"012",skill:"포켓몬 마스터의 기행",flavor:"전장을 지키는 영웅처럼 자신만의 기행을 이어간다.",accent:"#ff8ca5",palette:"monster",artwork:"/cards/yoonganom-super-rare-art.png"}
};
const english:Record<string,string>={침착맨:"CHIMCHAKMAN",랄로:"RALO",곽튜브:"KWAK TUBE",빠더너스:"BDNS",감스트:"GAMST",피식대학:"PSICK UNIV.",숏박스:"SHORT BOX",지무비:"G MOVIE",말왕:"MALWANG",보겸:"BOKYEM",떵개떵:"TTEONG",윤가놈:"YOONGANOM"};
const nameOf=(item:Element)=>item.querySelector(".tcg-shell__name strong")?.textContent||item.querySelector("img")?.alt.replace(" 완성 카드","")||"";

export default function GalleryEnhancer(){const[names,setNames]=useState<string[]>([]),[index,setIndex]=useState(-1),[tilt,setTilt]=useState({x:0,y:0}),start=useRef(0);useEffect(()=>{const open=(e:MouseEvent)=>{const item=(e.target as HTMLElement).closest(".result-item,.collection-card");if(!item)return;const all=[...document.querySelectorAll(".result-item,.collection-card")].map(nameOf).filter(Boolean),picked=nameOf(item);if(!picked)return;setNames(all);setIndex(all.indexOf(picked))};document.addEventListener("click",open);return()=>document.removeEventListener("click",open)},[]);if(index<0)return null;const name=names[index],card=cardMap[name],next=(d:number)=>setIndex(v=>(v+d+names.length)%names.length),move=(e:React.PointerEvent)=>{const r=e.currentTarget.getBoundingClientRect();setTilt({x:(e.clientY-r.top-r.height/2)/-16,y:(e.clientX-r.left-r.width/2)/16})};if(!card)return null;return <div className="gallery-modal" role="dialog" aria-modal="true" onClick={()=>setIndex(-1)}><button className="gallery-close" aria-label="닫기">×</button><button className="gallery-arrow left" onClick={e=>{e.stopPropagation();next(-1)}}>‹</button><div className="gallery-stage" onClick={e=>e.stopPropagation()} onPointerMove={move} onPointerLeave={()=>setTilt({x:0,y:0})} onPointerDown={e=>start.current=e.clientX} onPointerUp={e=>{if(Math.abs(e.clientX-start.current)>45)next(e.clientX<start.current?1:-1)}}><div className="gallery-card" style={{transform:`rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)`}}>{card.completed?<img className="gallery-complete" src={card.completed} alt={`${name} 카드`}/>:<CardShell name={card.name} englishName={english[name]} rarity={card.rarity} serial={`STX-YT01-${card.no}-000001`} skill={card.skill} flavor={card.flavor} artwork={card.artwork} accent={card.accent} palette={card.palette}/>}</div><p className="gallery-count">{index+1} / {names.length} · SWIPE TO BROWSE</p></div><button className="gallery-arrow right" onClick={e=>{e.stopPropagation();next(1)}}>›</button></div>}
