"use client";
import "./opening.css";
import "./pack.css";
import "./depth.css";
import "./stack.css";
import "./reveal-flow.css";
import { PointerEvent, useMemo, useRef, useState } from "react";

type Rarity = "COMMON" | "RARE" | "SUPER RARE" | "SECRET RARE";
type Card = { no:string; name:string; rarity:Rarity; flavor:string; scene:string; palette:string };
type Opening = "shop" | "tear" | "deal" | "result";
const cards:Card[]=[
  {no:"001",name:"침착맨",rarity:"SECRET RARE",flavor:"방구석 토크",scene:"왕좌와 펜, 무표정의 명언",palette:"royal"},{no:"002",name:"랄로",rarity:"SECRET RARE",flavor:"주식과 무지개 무드",scene:"화면 너머, 해탈한 표정",palette:"rainbow"},{no:"003",name:"곽튜브",rarity:"SUPER RARE",flavor:"세계 로컬 식사",scene:"낯선 도시의 식탁",palette:"sunset"},{no:"004",name:"빠더너스",rarity:"SUPER RARE",flavor:"한국 지리 문쌤",scene:"칠판 앞의 능청스러운 한 컷",palette:"chalk"},{no:"005",name:"감스트",rarity:"SUPER RARE",flavor:"축구치킨 광기",scene:"골이 터진 직후의 세레머니",palette:"stadium"},{no:"006",name:"피식대학",rarity:"RARE",flavor:"성수동 바이브",scene:"레트로 셔츠와 도시의 밤",palette:"retro"},{no:"007",name:"숏박스",rarity:"RARE",flavor:"현실 연애 콩트",scene:"차 안의 아주 현실적인 대화",palette:"drive"},{no:"008",name:"지무비",rarity:"RARE",flavor:"결말 포함 영화",scene:"필름과 스크린 사이",palette:"film"},{no:"009",name:"말왕",rarity:"COMMON",flavor:"3대 500 괴력",scene:"철과 숨소리만 남은 체육관",palette:"gym"},{no:"010",name:"보겸",rarity:"COMMON",flavor:"근황 올림픽",scene:"카메라를 향한 한 번의 인사",palette:"flash"},{no:"011",name:"떵개떵",rarity:"COMMON",flavor:"소리 없는 아우성",scene:"가득 찬 식탁의 ASMR",palette:"table"},{no:"012",name:"윤가놈",rarity:"COMMON",flavor:"포켓몬 마스터의 기행",scene:"몬스터볼과 이해할 수 없는 가설",palette:"monster"}
];
const short=(r:Rarity)=>r==="SUPER RARE"?"SR":r==="SECRET RARE"?"SS":r[0];
function CardFace({card,serial,small=false}:{card:Card;serial:number;small?:boolean}){return <article className={`stardex-card ${card.rarity.toLowerCase().replaceAll(" ","-")} ${small?"is-small":""}`}><div className={`art art-${card.palette}`}><div className="art-grid"/><p className="art-scene">{card.scene}</p><div className="art-orb one"/><div className="art-orb two"/></div><div className="card-top"><span>STX / YT-01</span><span>✦</span></div><div className="card-info"><div><p className="card-name">{card.name}</p><p className="card-flavor">{card.flavor}</p></div><span className="rarity-badge">{short(card.rarity)}</span><div className="serial">STX-01-{card.no}-{String(serial).padStart(6,"0")}</div></div></article>}
function CardBack({index,flipped,children}:{index:number;flipped:boolean;children:React.ReactNode}){return <button className={`reveal-card ${flipped?"flipped":""}`} style={{"--i":index} as React.CSSProperties} aria-label={`${index+1}번째 카드 공개`}><span className="reveal-inner"><span className="card-back"><b>STARDEX</b><i>✦</i><small>YOUTUBE CREATORS · VOL.01</small></span><span className="card-front">{children}</span></span></button>}
export default function Home(){
  const [coin,setCoin]=useState(3000),[pulls,setPulls]=useState<Card[]>([]),[opening,setOpening]=useState<Opening>("shop"),[pack,setPack]=useState<Card[]>([]),[flipped,setFlipped]=useState<number[]>([]),[view,setView]=useState<"shop"|"collection">("shop"),[drag,setDrag]=useState(0); const start=useRef(0);
  const owned=useMemo(()=>new Set(pulls.map(c=>c.no)),[pulls]);
  const draw=(guaranteed=false)=>{const roll=Math.random()*100;const r=guaranteed?(roll<70?"RARE":roll<94?"SUPER RARE":"SECRET RARE"):(roll<60?"COMMON":roll<85?"RARE":roll<97?"SUPER RARE":"SECRET RARE");const pool=cards.filter(c=>c.rarity===r);return pool[Math.floor(Math.random()*pool.length)]};
  const buy=()=>{if(coin<1000)return;setCoin(v=>v-1000);setPack([draw(),draw(),draw(),draw(),draw(true)]);setFlipped([]);setDrag(0);setOpening("tear")};
  const begin=(e:PointerEvent<HTMLDivElement>)=>{start.current=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)};
  const move=(e:PointerEvent<HTMLDivElement>)=>{if(!start.current)return;const next=Math.max(0,Math.min(100,(start.current-e.clientY)*1.25));setDrag(next);if(next>=100){start.current=0;setTimeout(()=>setOpening("deal"),180)}};
  const end=()=>{if(drag<100)setDrag(0);start.current=0};
  const flip=(index:number)=>{if(flipped.includes(index))return;const next=[...flipped,index];setFlipped(next);if(pack[index].rarity!=="COMMON"&&pack[index].rarity!=="RARE")document.body.classList.add("rare-flash");setTimeout(()=>document.body.classList.remove("rare-flash"),700);if(next.length===5){setPulls(v=>[...v,...pack]);setTimeout(()=>setOpening("result"),800)}};
  const reset=()=>{setOpening("shop");setPack([]);setFlipped([])};
  return <main className="app-shell"><nav className="topbar"><a className="logo" href="#top" onClick={()=>{setView("shop");reset()}}>STARDEX</a><div className="nav-links"><button className={view==="shop"?"active":""} onClick={()=>{setView("shop");reset()}}>PACK SHOP</button><button className={view==="collection"?"active":""} onClick={()=>setView("collection")}>COLLECTION <em>{owned.size}/12</em></button></div><div className="balance"><span>◇</span>{coin.toLocaleString()} COIN</div></nav>{view==="collection"?<Collection owned={owned}/>:opening==="shop"?<Shop coin={coin} buy={buy}/>:<OpeningFlow mode={opening} pack={pack} drag={drag} flipped={flipped} begin={begin} move={move} end={end} flip={flip} reset={reset} owned={owned}/>}<footer>STARDEX is a non-commercial fan project. © 2026</footer></main>
}
function Shop({coin,buy}:{coin:number;buy:()=>void}){return <section id="top" className="shop-view"><p className="eyebrow">SEASON 01 · YOUTUBE CREATORS</p><h1>YOU TUBE<br/><i>PACK VOL. 1</i></h1><p className="intro">크리에이터의 장면을 모으세요. 모든 카드는 각자의 시리얼을 가집니다.</p><div className="shop-stage"><div className="pack-box"><div className="pack-shine"/><span>STARDEX</span><strong>YOUTUBE<br/>CREATORS</strong><small>VOL. 01 · 5 CARDS</small></div><div className="shop-copy"><b>첫 번째 컬렉션</b><p>12명의 크리에이터,<br/>12개의 다른 장면.</p><span>5 CARDS PER PACK</span></div></div><div className="open-area"><button className="open-button" onClick={buy} disabled={coin<1000}>BUY & OPEN <span>1,000 ◇</span></button><p>5 CARDS · 마지막 카드는 RARE 이상 보장</p></div></section>}
function OpeningFlow({mode,pack,drag,flipped,begin,move,end,flip,reset,owned}:{mode:Opening;pack:Card[];drag:number;flipped:number[];begin:(e:PointerEvent<HTMLDivElement>)=>void;move:(e:PointerEvent<HTMLDivElement>)=>void;end:()=>void;flip:(i:number)=>void;reset:()=>void;owned:Set<string>}){if(mode==="tear")return <section className="opening-screen"><p className="eyebrow">TEAR TO OPEN</p><h2>위로 밀어서<br/><i>팩을 뜯으세요.</i></h2><div className="tear-zone" onPointerDown={begin} onPointerMove={move} onPointerUp={end} onPointerCancel={end}><div className="tear-pack" style={{transform:`translateY(${-drag*.45}px)`,clipPath:`polygon(0 ${drag*.45}%,100% 0,100% 100%,0 100%)`}}><span>STARDEX</span><strong>YOUTUBE<br/>CREATORS</strong><small>DRAG ↑</small></div><div className="tear-line" style={{bottom:`${drag}%`}}/></div><p className="drag-hint">{drag?`${Math.round(drag)}%`:`SWIPE UP`}</p></section>;if(mode==="deal")return <section className="opening-screen deal-screen"><p className="eyebrow">TAP EACH CARD TO REVEAL</p><h2>무엇이 나왔을까.</h2><div className="reveal-fan">{pack.map((card,index)=><div key={`${card.no}-${index}`} onClick={()=>flip(index)}><CardBack index={index} flipped={flipped.includes(index)}><CardFace card={card} serial={pullsSerial(index)}/></CardBack></div>)}</div><p className="drag-hint">{flipped.length} / 5 REVEALED</p></section>;const fresh=pack.filter(c=>!owned.has(c.no)).length;return <section className="result-screen"><p className="eyebrow">PACK RESULTS</p><h2>COLLECTION<br/><i>UPDATED</i></h2><div className="result-grid">{pack.map((card,index)=><div className="result-item" key={`${card.no}-${index}`}><CardFace card={card} serial={pullsSerial(index)} small/><b className={owned.has(card.no)?"duplicate":"new"}>{owned.has(card.no)?"DUPLICATE +1":"NEW"}</b></div>)}</div><p className="summary"><b>{fresh} NEW CARD{fresh===1?"":"S"}</b> · 중복 카드는 추후 Dust로 분해할 수 있어요.</p><button className="open-button" onClick={reset}>BACK TO SHOP</button></section>}
const pullsSerial=(index:number)=>Math.floor(Date.now()/1000)%100000+index;
function Collection({owned}:{owned:Set<string>}){return <section className="collection-view"><header><div><p className="eyebrow">MY ARCHIVE</p><h1>YOU TUBE<br/><i>COLLECTION</i></h1></div><p className="progress"><b>{owned.size}</b> / 12<br/><span>CARDS DISCOVERED</span></p></header><div className="collection-grid">{cards.map((card,index)=>owned.has(card.no)?<button key={card.no} className="collection-card"><CardFace card={card} serial={index+1} small/></button>:<div className="locked-card" key={card.no}><span>?</span><p>NO. {card.no}</p></div>)}</div></section>}
