"use client";

import { useEffect, useRef, useState } from "react";
import { Bell } from "lucide-react";

type Notice = { id: string; type: string; title: string; body: string; cardId: string | null; relatedId: string | null; readAt: string | null; createdAt: string; artworkUrl: string | null; rarity: string | null; cardName: string | null; data: Record<string, unknown> };
type Props = { active: boolean; onOpenExchange: () => void; onCollectionRefresh: () => Promise<void> };
const labels: Record<string, string> = { COMMON: "C", RARE: "R", "SUPER RARE": "SR", MR: "MR", UR: "UR", BR: "BR" };
function relativeTime(value: string) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(`${value.endsWith("Z") ? value : `${value}Z`}`).getTime()) / 1000)); return seconds < 60 ? "방금 전" : seconds < 3600 ? `${Math.floor(seconds / 60)}분 전` : seconds < 86400 ? `${Math.floor(seconds / 3600)}시간 전` : `${Math.floor(seconds / 86400)}일 전`; }

export function NotificationCenter({ active, onOpenExchange, onCollectionRefresh }: Props) {
  const [open, setOpen] = useState(false), [items, setItems] = useState<Notice[]>([]), [modal, setModal] = useState<Notice | null>(null), [pending, setPending] = useState<string | null>(null);
  const shown = useRef(new Set<string>());
  const refresh = async () => { const response = await fetch("/api/notifications"); if (!response.ok) return; const data = await response.json() as { notifications: Notice[] }; setItems(data.notifications); const next = data.notifications.find((item) => item.type === "TRADE_REQUEST" && !item.readAt && !shown.current.has(item.id)); if (next) { shown.current.add(next.id); setModal(next); } };
  useEffect(() => { if (!active) return; const initial = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 30000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [active]);
  const unread = items.filter((item) => !item.readAt).length;
  const markRead = async (id: string) => { await fetch("/api/notifications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "read", notificationId: id }) }); await refresh(); };
  const markAllRead = async () => { await fetch("/api/notifications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "read-all" }) }); await refresh(); };
  const respond = async (notice: Notice, action: "accept" | "decline") => { const requestId = String(notice.data.requestId ?? notice.relatedId ?? ""); if (!requestId) return; setPending(`${action}:${notice.id}`); try { const response = await fetch("/api/marketplace", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, requestId }) }); if (response.ok) { await Promise.all([refresh(), onCollectionRefresh()]); setModal(null); } } finally { setPending(null); } };
  const inspect = async (notice: Notice) => { await markRead(notice.id); setModal(null); setOpen(false); onOpenExchange(); };
  if (!active) return null;
  return <><button className="notification-bell" onClick={() => setOpen(true)} aria-label={`알림 ${unread ? `${unread}개 읽지 않음` : ""}`}><Bell aria-hidden="true" size={18} strokeWidth={1.6}/>{unread > 0 && <b>{unread > 9 ? "9+" : unread}</b>}</button>
    {open && <><button className="notification-scrim" aria-label="알림 패널 닫기" onClick={() => setOpen(false)} /><aside className="notification-drawer" aria-label="알림센터"><header><div><p>알림센터</p><h2>NOTIFICATIONS</h2></div><button onClick={() => setOpen(false)} aria-label="닫기">×</button></header><div className="notification-drawer__tools"><span>{unread ? `읽지 않은 알림 ${unread}개` : "새 알림이 없습니다"}</span><button onClick={() => void markAllRead()} disabled={!unread}>모두 읽음</button></div><div className="notification-list">{items.length ? items.map((notice) => <article className={`notification-card ${notice.readAt ? "" : "is-unread"}`} key={notice.id} onClick={() => void markRead(notice.id)}><div className="notification-card__art">{notice.artworkUrl ? <img src={notice.artworkUrl} alt="" /> : <span>✦</span>}</div><div><p>{notice.type.replaceAll("_", " ")} <time>{relativeTime(notice.createdAt)}</time></p><strong>{notice.title}</strong><span>{notice.body}</span>{notice.type === "TRADE_REQUEST" && <em>{String(notice.data.offeredName ?? notice.cardName ?? "카드")} {labels[String(notice.data.offeredRarity ?? notice.rarity ?? "")] ?? ""} ↔ {String(notice.data.requestedName ?? "내 카드")} {labels[String(notice.data.requestedRarity ?? "")] ?? ""}</em>}{notice.type === "TRADE_REQUEST" && <footer onClick={(event) => event.stopPropagation()}><button onClick={() => void respond(notice, "accept")} disabled={pending === `accept:${notice.id}`}>수락</button><button onClick={() => void respond(notice, "decline")} disabled={pending === `decline:${notice.id}`}>거절</button></footer>}</div></article>) : <p className="notification-empty">아직 도착한 알림이 없습니다.</p>}</div></aside></>}
    {modal && <div className="notification-modal" role="dialog" aria-modal="true" aria-label="새 교환 요청"><section><p>NEW TRADE REQUEST</p><h2>새 교환 요청</h2><div className="notification-modal__pair"><strong>{String(modal.data.offeredName ?? modal.cardName ?? "카드")} <small>{labels[String(modal.data.offeredRarity ?? modal.rarity ?? "")] ?? ""}</small></strong><i>↕</i><strong>{String(modal.data.requestedName ?? "내 카드")} <small>{labels[String(modal.data.requestedRarity ?? "")] ?? ""}</small></strong></div><p>{modal.body}</p><footer><button onClick={() => void inspect(modal)}>자세히 보기</button><button className="notification-modal__later" onClick={() => setModal(null)}>나중에</button></footer></section></div>}
  </>;
}
